#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'


cookbook 'openssl'
cookbook 'nagios'
cookbook 'tomcat',:git => 'https://github.com/opscode-cookbooks/tomcat'
cookbook 'nginx', :git => 'git://github.com/opscode-cookbooks/nginx.git'
cookbook 'monit', :git => 'https://github.com/phlipper/chef-monit.git'
cookbook 'cassandra', :git =>  'https://github.com/michaelklishin/cassandra-chef-cookbook'
cookbook 'ruby_build', :github => 'fnichol/chef-rvm'
cookbook 'postfix'
cookbook 'chef_solo_env', :path => '/root/cookbooks/chef_solo_env'





# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
